# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_click = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_click.setGeometry(QtCore.QRect(130, 470, 500, 100))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.pushButton_click.setFont(font)
        self.pushButton_click.setStyleSheet("background-color: rgb(35, 233, 255);\n"
"color:rgb(255,255,255);")
        self.pushButton_click.setObjectName("pushButton_click")
        self.click_count_label = QtWidgets.QLabel(self.centralwidget)
        self.click_count_label.setGeometry(QtCore.QRect(160, 160, 421, 111))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.click_count_label.setFont(font)
        self.click_count_label.setObjectName("click_count_label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_click.setText(_translate("MainWindow", "Click Me"))
        self.click_count_label.setText(_translate("MainWindow", "No of Clicks: 0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
